[alias]
b = "build --lib --bins --features bin"
t = "test --target aarch64-apple-darwin --lib"

[target.thumbv8m.main-none-eabihf]
runner = [
  "probe-rs",
  "run",
  "--chip",
  "RP235x",
  "--protocol",
  "swd",
  "--log-format", "{L:severity} {s}"
]

rustflags = [
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tdefmt.x",
    "-C", "target-cpu=cortex-m33",
]

[build]
target = "thumbv8m.main-none-eabihf" 

[env]
DEFMT_LOG = "debug"
