[alias]
t = "test --no-default-features --features log --target aarch64-apple-darwin"

[target.thumbv8m.main-none-eabihf]
runner = [
  "probe-rs",
  "run",
  "--chip",
  "RP235x",
  "--protocol",
  "swd",
  "--log-format", "{L:severity} {s}"
]

rustflags = [
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tdefmt.x",
    "-C", "target-cpu=cortex-m33",
]

[build]
target = "thumbv8m.main-none-eabihf"

[env]
DEFMT_LOG = "debug"
RUST_LOG = "debug"

WIFI_SSID="replaced"
WIFI_PASSWORD="replaced"
