[alias]
b = "build --target thumbv8m.main-none-eabihf --lib --bins --features bin --no-default-features"

[target.thumbv8m.main-none-eabihf]
runner = [
  "probe-rs",
  "run",
  "--chip",
  "RP235x",
  "--protocol",
  "swd",
  "--log-format", "{L:severity} {s}"
]

rustflags = [
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tdefmt.x",
    "-C", "target-cpu=cortex-m33",
]

[env]
DEFMT_LOG = "debug"
RUST_LOG = "debug"
