[alias]
run-baked="run --features baked-cyw43"
t = "test --no-default-features --features log --target aarch64-apple-darwin"

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
linker = "flip-link"

[target.thumbv8m.main-none-eabihf]
runner = [
  "probe-rs",
  "run",
  "--chip",
  "RP235x",
  "--protocol",
  "swd",
  "--log-format", "[{L:severity}] {f:>10}:{l} | {s}"
]

rustflags = [
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tdefmt.x",
    "-C", "target-cpu=cortex-m33",
]

[build]
target = "thumbv8m.main-none-eabihf"

[env]
DEFMT_LOG = "debug"
RUST_LOG = "warn"

WIFI_SSID="replaced"
WIFI_PASSWORD="replaced"
