name: Tests

on:
  push:
    branches: [ main ]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  WIFI_SSID: "test-network"
  WIFI_PASSWORD: "test-password"

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@1.90.0
      with:
        targets: x86_64-unknown-linux-gnu

    - name: Cache cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-test-

    - name: Run tests
      run: cargo test --target x86_64-unknown-linux-gnu --no-default-features --features log
